Vagrant.configure(2) do |config|
  #config.vm.box = "ubuntu/trusty64"
  config.vm.box = "alvaro/ubuntu1402-ruby222"
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.synced_folder "..", "/srv/railsapp", create: true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
  config.vm.provision "shell", privileged: false, path: "provision.sh"
  
  #For private network
  #config.vm.network "private_network", ip: "192.168.50.4"

  #For public network
  #config.vm.network "public_network", ip: "192.168.0.17"

end
